//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "FK_cities_departments", "Departments", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Territories.Model.Department), "Cities", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.City))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "FK_directions_cities", "Cities", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Territories.Model.City), "Directions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Direction))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "FK_publishers_cities", "Cities", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Territories.Model.City), "Publishers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Publisher))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "FK_directions_territories", "Territories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Territories.Model.Territory), "Directions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Direction))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "FK_tours_publishers", "Publishers", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Territories.Model.Publisher), "Tours", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Tour))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "FK_tours_territories", "Territories", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Territories.Model.Territory), "Tours", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Tour))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "CitiesGeopositions", "City", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.City), "GeoPositions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.GeoPosition))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "DepartmentsGeopositions", "Department", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Department), "GeoPositions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.GeoPosition))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "DirectionsGeopositions", "Direction", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Direction), "GeoPositions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.GeoPosition))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TerritoriesModel", "TerritoriesGeopositions", "GeoPositions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.GeoPosition), "Territory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Territories.Model.Territory))]

// Original file name:
// Generation date: 15/07/2009 07:13:23 p.m.
namespace Territories.Model
{
    
    /// <summary>
    /// There are no comments for TerritoriesDataContext in the schema.
    /// </summary>
    public partial class TerritoriesDataContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TerritoriesDataContext object using the connection string found in the 'TerritoriesDataContext' section of the application configuration file.
        /// </summary>
        public TerritoriesDataContext() : 
                base("name=TerritoriesDataContext", "TerritoriesDataContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TerritoriesDataContext object.
        /// </summary>
        public TerritoriesDataContext(string connectionString) : 
                base(connectionString, "TerritoriesDataContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new TerritoriesDataContext object.
        /// </summary>
        public TerritoriesDataContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TerritoriesDataContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<City> Cities
        {
            get
            {
                if ((this._Cities == null))
                {
                    this._Cities = base.CreateQuery<City>("[Cities]");
                }
                return this._Cities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<City> _Cities;
        /// <summary>
        /// There are no comments for Departments in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Department> Departments
        {
            get
            {
                if ((this._Departments == null))
                {
                    this._Departments = base.CreateQuery<Department>("[Departments]");
                }
                return this._Departments;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Department> _Departments;
        /// <summary>
        /// There are no comments for Directions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Direction> Directions
        {
            get
            {
                if ((this._Directions == null))
                {
                    this._Directions = base.CreateQuery<Direction>("[Directions]");
                }
                return this._Directions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Direction> _Directions;
        /// <summary>
        /// There are no comments for Publishers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Publisher> Publishers
        {
            get
            {
                if ((this._Publishers == null))
                {
                    this._Publishers = base.CreateQuery<Publisher>("[Publishers]");
                }
                return this._Publishers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Publisher> _Publishers;
        /// <summary>
        /// There are no comments for Territories in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Territory> Territories
        {
            get
            {
                if ((this._Territories == null))
                {
                    this._Territories = base.CreateQuery<Territory>("[Territories]");
                }
                return this._Territories;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Territory> _Territories;
        /// <summary>
        /// There are no comments for Tours in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tour> Tours
        {
            get
            {
                if ((this._Tours == null))
                {
                    this._Tours = base.CreateQuery<Tour>("[Tours]");
                }
                return this._Tours;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tour> _Tours;
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<GeoPosition> GeoPositions
        {
            get
            {
                if ((this._GeoPositions == null))
                {
                    this._GeoPositions = base.CreateQuery<GeoPosition>("[GeoPositions]");
                }
                return this._GeoPositions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<GeoPosition> _GeoPositions;
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        public void AddToCities(City city)
        {
            base.AddObject("Cities", city);
        }
        /// <summary>
        /// There are no comments for Departments in the schema.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
        /// <summary>
        /// There are no comments for Directions in the schema.
        /// </summary>
        public void AddToDirections(Direction direction)
        {
            base.AddObject("Directions", direction);
        }
        /// <summary>
        /// There are no comments for Publishers in the schema.
        /// </summary>
        public void AddToPublishers(Publisher publisher)
        {
            base.AddObject("Publishers", publisher);
        }
        /// <summary>
        /// There are no comments for Territories in the schema.
        /// </summary>
        public void AddToTerritories(Territory territory)
        {
            base.AddObject("Territories", territory);
        }
        /// <summary>
        /// There are no comments for Tours in the schema.
        /// </summary>
        public void AddToTours(Tour tour)
        {
            base.AddObject("Tours", tour);
        }
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        public void AddToGeoPositions(GeoPosition geoPosition)
        {
            base.AddObject("GeoPositions", geoPosition);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.departments_GetAll in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Department> departments_GetAll()
        {
            return base.ExecuteFunction<Department>("departments_GetAll");
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.cities_GetAll in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<City> cities_GetAll()
        {
            return base.ExecuteFunction<City>("cities_GetAll");
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.departments_GetById in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Department> departments_GetById(global::System.Nullable<int> id)
        {
            global::System.Data.Objects.ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", id);
            }
            else
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", typeof(int));
            }
            return base.ExecuteFunction<Department>("departments_GetById", idParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.cities_GetById in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<City> cities_GetById(global::System.Nullable<int> id)
        {
            global::System.Data.Objects.ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", id);
            }
            else
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", typeof(int));
            }
            return base.ExecuteFunction<City>("cities_GetById", idParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.directions_GetAll in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Direction> directions_GetAll()
        {
            return base.ExecuteFunction<Direction>("directions_GetAll");
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.directions_GetByCity in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Direction> directions_GetByCity(global::System.Nullable<int> idCity)
        {
            global::System.Data.Objects.ObjectParameter idCityParameter;
            if (idCity.HasValue)
            {
                idCityParameter = new global::System.Data.Objects.ObjectParameter("idCity", idCity);
            }
            else
            {
                idCityParameter = new global::System.Data.Objects.ObjectParameter("idCity", typeof(int));
            }
            return base.ExecuteFunction<Direction>("directions_GetByCity", idCityParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.cities_GetByDepartment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<City> cities_GetByDepartment(global::System.Nullable<int> idDepartment)
        {
            global::System.Data.Objects.ObjectParameter idDepartmentParameter;
            if (idDepartment.HasValue)
            {
                idDepartmentParameter = new global::System.Data.Objects.ObjectParameter("idDepartment", idDepartment);
            }
            else
            {
                idDepartmentParameter = new global::System.Data.Objects.ObjectParameter("idDepartment", typeof(int));
            }
            return base.ExecuteFunction<City>("cities_GetByDepartment", idDepartmentParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.publishers_GetByCity in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Publisher> publishers_GetByCity(global::System.Nullable<int> idCity)
        {
            global::System.Data.Objects.ObjectParameter idCityParameter;
            if (idCity.HasValue)
            {
                idCityParameter = new global::System.Data.Objects.ObjectParameter("idCity", idCity);
            }
            else
            {
                idCityParameter = new global::System.Data.Objects.ObjectParameter("idCity", typeof(int));
            }
            return base.ExecuteFunction<Publisher>("publishers_GetByCity", idCityParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.territories_GetById in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Territory> territories_GetById(global::System.Nullable<int> id)
        {
            global::System.Data.Objects.ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", id);
            }
            else
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", typeof(int));
            }
            return base.ExecuteFunction<Territory>("territories_GetById", idParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.territories_GetAll in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Territory> territories_GetAll()
        {
            return base.ExecuteFunction<Territory>("territories_GetAll");
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.territories_Add in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Territory> territories_Add(string name, global::System.Nullable<int> number)
        {
            global::System.Data.Objects.ObjectParameter nameParameter;
            if ((name != null))
            {
                nameParameter = new global::System.Data.Objects.ObjectParameter("name", name);
            }
            else
            {
                nameParameter = new global::System.Data.Objects.ObjectParameter("name", typeof(string));
            }
            global::System.Data.Objects.ObjectParameter numberParameter;
            if (number.HasValue)
            {
                numberParameter = new global::System.Data.Objects.ObjectParameter("number", number);
            }
            else
            {
                numberParameter = new global::System.Data.Objects.ObjectParameter("number", typeof(int));
            }
            return base.ExecuteFunction<Territory>("territories_Add", nameParameter, numberParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.territories_UpdateById in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Territory> territories_UpdateById(global::System.Nullable<int> id, string name, global::System.Nullable<int> number)
        {
            global::System.Data.Objects.ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", id);
            }
            else
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter nameParameter;
            if ((name != null))
            {
                nameParameter = new global::System.Data.Objects.ObjectParameter("name", name);
            }
            else
            {
                nameParameter = new global::System.Data.Objects.ObjectParameter("name", typeof(string));
            }
            global::System.Data.Objects.ObjectParameter numberParameter;
            if (number.HasValue)
            {
                numberParameter = new global::System.Data.Objects.ObjectParameter("number", number);
            }
            else
            {
                numberParameter = new global::System.Data.Objects.ObjectParameter("number", typeof(int));
            }
            return base.ExecuteFunction<Territory>("territories_UpdateById", idParameter, nameParameter, numberParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.territories_DeleteById in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Territory> territories_DeleteById(global::System.Nullable<int> id)
        {
            global::System.Data.Objects.ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", id);
            }
            else
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", typeof(int));
            }
            return base.ExecuteFunction<Territory>("territories_DeleteById", idParameter);
        }
        /// <summary>
        /// There are no comments for TerritoriesModel.directions_GetById in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Direction> directions_GetById(global::System.Nullable<int> id)
        {
            global::System.Data.Objects.ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", id);
            }
            else
            {
                idParameter = new global::System.Data.Objects.ObjectParameter("id", typeof(int));
            }
            return base.ExecuteFunction<Direction>("directions_GetById", idParameter);
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.City in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdCity
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="City")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class City : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="idCity">Initial value of IdCity.</param>
        /// <param name="name">Initial value of Name.</param>
        public static City CreateCity(int idCity, string name)
        {
            City city = new City();
            city.IdCity = idCity;
            city.Name = name;
            return city;
        }
        /// <summary>
        /// There are no comments for Property IdCity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCity
        {
            get
            {
                return this._IdCity;
            }
            set
            {
                this.OnIdCityChanging(value);
                this.ReportPropertyChanging("IdCity");
                this._IdCity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCity");
                this.OnIdCityChanged();
            }
        }
        private int _IdCity;
        partial void OnIdCityChanging(int value);
        partial void OnIdCityChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_cities_departments", "Departments")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Department Department
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("TerritoriesModel.FK_cities_departments", "Departments").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("TerritoriesModel.FK_cities_departments", "Departments").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("TerritoriesModel.FK_cities_departments", "Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Department>("TerritoriesModel.FK_cities_departments", "Departments", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Directions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_directions_cities", "Directions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Direction> Directions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Direction>("TerritoriesModel.FK_directions_cities", "Directions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Direction>("TerritoriesModel.FK_directions_cities", "Directions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Publishers in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_publishers_cities", "Publishers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Publisher> Publishers
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Publisher>("TerritoriesModel.FK_publishers_cities", "Publishers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Publisher>("TerritoriesModel.FK_publishers_cities", "Publishers", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "CitiesGeopositions", "GeoPositions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GeoPosition> GeoPositions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GeoPosition>("TerritoriesModel.CitiesGeopositions", "GeoPositions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GeoPosition>("TerritoriesModel.CitiesGeopositions", "GeoPositions", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.Department in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdDepartment
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="Department")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Department : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="idDepartment">Initial value of IdDepartment.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Department CreateDepartment(int idDepartment, string name)
        {
            Department department = new Department();
            department.IdDepartment = idDepartment;
            department.Name = name;
            return department;
        }
        /// <summary>
        /// There are no comments for Property IdDepartment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartment
        {
            get
            {
                return this._IdDepartment;
            }
            set
            {
                this.OnIdDepartmentChanging(value);
                this.ReportPropertyChanging("IdDepartment");
                this._IdDepartment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdDepartment");
                this.OnIdDepartmentChanged();
            }
        }
        private int _IdDepartment;
        partial void OnIdDepartmentChanging(int value);
        partial void OnIdDepartmentChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_cities_departments", "Cities")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<City> Cities
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<City>("TerritoriesModel.FK_cities_departments", "Cities");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<City>("TerritoriesModel.FK_cities_departments", "Cities", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "DepartmentsGeopositions", "GeoPositions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GeoPosition> GeoPositions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GeoPosition>("TerritoriesModel.DepartmentsGeopositions", "GeoPositions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GeoPosition>("TerritoriesModel.DepartmentsGeopositions", "GeoPositions", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.Direction in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdDirection
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="Direction")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Direction : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Direction object.
        /// </summary>
        /// <param name="idDirection">Initial value of IdDirection.</param>
        /// <param name="street">Initial value of Street.</param>
        public static Direction CreateDirection(int idDirection, string street)
        {
            Direction direction = new Direction();
            direction.IdDirection = idDirection;
            direction.Street = street;
            return direction;
        }
        /// <summary>
        /// There are no comments for Property IdDirection in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDirection
        {
            get
            {
                return this._IdDirection;
            }
            set
            {
                this.OnIdDirectionChanging(value);
                this.ReportPropertyChanging("IdDirection");
                this._IdDirection = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdDirection");
                this.OnIdDirectionChanged();
            }
        }
        private int _IdDirection;
        partial void OnIdDirectionChanging(int value);
        partial void OnIdDirectionChanged();
        /// <summary>
        /// There are no comments for Property Corner1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Corner1
        {
            get
            {
                return this._Corner1;
            }
            set
            {
                this.OnCorner1Changing(value);
                this.ReportPropertyChanging("Corner1");
                this._Corner1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Corner1");
                this.OnCorner1Changed();
            }
        }
        private string _Corner1;
        partial void OnCorner1Changing(string value);
        partial void OnCorner1Changed();
        /// <summary>
        /// There are no comments for Property Corner2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Corner2
        {
            get
            {
                return this._Corner2;
            }
            set
            {
                this.OnCorner2Changing(value);
                this.ReportPropertyChanging("Corner2");
                this._Corner2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Corner2");
                this.OnCorner2Changed();
            }
        }
        private string _Corner2;
        partial void OnCorner2Changing(string value);
        partial void OnCorner2Changed();
        /// <summary>
        /// There are no comments for Property Phone1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1
        {
            get
            {
                return this._Phone1;
            }
            set
            {
                this.OnPhone1Changing(value);
                this.ReportPropertyChanging("Phone1");
                this._Phone1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone1");
                this.OnPhone1Changed();
            }
        }
        private string _Phone1;
        partial void OnPhone1Changing(string value);
        partial void OnPhone1Changed();
        /// <summary>
        /// There are no comments for Property Phone2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2
        {
            get
            {
                return this._Phone2;
            }
            set
            {
                this.OnPhone2Changing(value);
                this.ReportPropertyChanging("Phone2");
                this._Phone2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone2");
                this.OnPhone2Changed();
            }
        }
        private string _Phone2;
        partial void OnPhone2Changing(string value);
        partial void OnPhone2Changed();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Map1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Map1
        {
            get
            {
                return this._Map1;
            }
            set
            {
                this.OnMap1Changing(value);
                this.ReportPropertyChanging("Map1");
                this._Map1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Map1");
                this.OnMap1Changed();
            }
        }
        private string _Map1;
        partial void OnMap1Changing(string value);
        partial void OnMap1Changed();
        /// <summary>
        /// There are no comments for Property Map2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Map2
        {
            get
            {
                return this._Map2;
            }
            set
            {
                this.OnMap2Changing(value);
                this.ReportPropertyChanging("Map2");
                this._Map2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Map2");
                this.OnMap2Changed();
            }
        }
        private string _Map2;
        partial void OnMap2Changing(string value);
        partial void OnMap2Changed();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this.ReportPropertyChanging("Number");
                this._Number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Number");
                this.OnNumberChanged();
            }
        }
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this.ReportPropertyChanging("Street");
                this._Street = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Street");
                this.OnStreetChanged();
            }
        }
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property CustomField1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField1
        {
            get
            {
                return this._CustomField1;
            }
            set
            {
                this.OnCustomField1Changing(value);
                this.ReportPropertyChanging("CustomField1");
                this._CustomField1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CustomField1");
                this.OnCustomField1Changed();
            }
        }
        private string _CustomField1;
        partial void OnCustomField1Changing(string value);
        partial void OnCustomField1Changed();
        /// <summary>
        /// There are no comments for Property CustomField2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField2
        {
            get
            {
                return this._CustomField2;
            }
            set
            {
                this.OnCustomField2Changing(value);
                this.ReportPropertyChanging("CustomField2");
                this._CustomField2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CustomField2");
                this.OnCustomField2Changed();
            }
        }
        private string _CustomField2;
        partial void OnCustomField2Changing(string value);
        partial void OnCustomField2Changed();
        /// <summary>
        /// There are no comments for Property DirectionData in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectionData
        {
            get
            {
                return this._DirectionData;
            }
            set
            {
                this.OnDirectionDataChanging(value);
                this.ReportPropertyChanging("DirectionData");
                this._DirectionData = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DirectionData");
                this.OnDirectionDataChanged();
            }
        }
        private string _DirectionData;
        partial void OnDirectionDataChanging(string value);
        partial void OnDirectionDataChanged();
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_directions_cities", "Cities")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public City City
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<City>("TerritoriesModel.FK_directions_cities", "Cities").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<City>("TerritoriesModel.FK_directions_cities", "Cities").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<City> CityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<City>("TerritoriesModel.FK_directions_cities", "Cities");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<City>("TerritoriesModel.FK_directions_cities", "Cities", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Territory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_directions_territories", "Territories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Territory Territory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Territory>("TerritoriesModel.FK_directions_territories", "Territories").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Territory>("TerritoriesModel.FK_directions_territories", "Territories").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Territory in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Territory> TerritoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Territory>("TerritoriesModel.FK_directions_territories", "Territories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Territory>("TerritoriesModel.FK_directions_territories", "Territories", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "DirectionsGeopositions", "GeoPositions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GeoPosition> GeoPositions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GeoPosition>("TerritoriesModel.DirectionsGeopositions", "GeoPositions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GeoPosition>("TerritoriesModel.DirectionsGeopositions", "GeoPositions", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.Publisher in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdPublisher
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="Publisher")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Publisher : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Publisher object.
        /// </summary>
        /// <param name="idPublisher">Initial value of IdPublisher.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="notes">Initial value of Notes.</param>
        public static Publisher CreatePublisher(int idPublisher, string name, string notes)
        {
            Publisher publisher = new Publisher();
            publisher.IdPublisher = idPublisher;
            publisher.Name = name;
            publisher.Notes = notes;
            return publisher;
        }
        /// <summary>
        /// There are no comments for Property IdPublisher in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPublisher
        {
            get
            {
                return this._IdPublisher;
            }
            set
            {
                this.OnIdPublisherChanging(value);
                this.ReportPropertyChanging("IdPublisher");
                this._IdPublisher = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPublisher");
                this.OnIdPublisherChanged();
            }
        }
        private int _IdPublisher;
        partial void OnIdPublisherChanging(int value);
        partial void OnIdPublisherChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Direction in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction
        {
            get
            {
                return this._Direction;
            }
            set
            {
                this.OnDirectionChanging(value);
                this.ReportPropertyChanging("Direction");
                this._Direction = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Direction");
                this.OnDirectionChanged();
            }
        }
        private string _Direction;
        partial void OnDirectionChanging(string value);
        partial void OnDirectionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this.ReportPropertyChanging("Notes");
                this._Notes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Notes");
                this.OnNotesChanged();
            }
        }
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Phone1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1
        {
            get
            {
                return this._Phone1;
            }
            set
            {
                this.OnPhone1Changing(value);
                this.ReportPropertyChanging("Phone1");
                this._Phone1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone1");
                this.OnPhone1Changed();
            }
        }
        private string _Phone1;
        partial void OnPhone1Changing(string value);
        partial void OnPhone1Changed();
        /// <summary>
        /// There are no comments for Property Phone2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2
        {
            get
            {
                return this._Phone2;
            }
            set
            {
                this.OnPhone2Changing(value);
                this.ReportPropertyChanging("Phone2");
                this._Phone2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Phone2");
                this.OnPhone2Changed();
            }
        }
        private string _Phone2;
        partial void OnPhone2Changing(string value);
        partial void OnPhone2Changed();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                this.ReportPropertyChanging("Zip");
                this._Zip = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Zip");
                this.OnZipChanged();
            }
        }
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_publishers_cities", "Cities")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public City City
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<City>("TerritoriesModel.FK_publishers_cities", "Cities").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<City>("TerritoriesModel.FK_publishers_cities", "Cities").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<City> CityReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<City>("TerritoriesModel.FK_publishers_cities", "Cities");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<City>("TerritoriesModel.FK_publishers_cities", "Cities", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tours in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_tours_publishers", "Tours")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tour> Tours
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tour>("TerritoriesModel.FK_tours_publishers", "Tours");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Tour>("TerritoriesModel.FK_tours_publishers", "Tours", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.Territory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdTerritory
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="Territory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Territory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Territory object.
        /// </summary>
        /// <param name="idTerritory">Initial value of IdTerritory.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Territory CreateTerritory(int idTerritory, string name)
        {
            Territory territory = new Territory();
            territory.IdTerritory = idTerritory;
            territory.Name = name;
            return territory;
        }
        /// <summary>
        /// There are no comments for Property IdTerritory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTerritory
        {
            get
            {
                return this._IdTerritory;
            }
            set
            {
                this.OnIdTerritoryChanging(value);
                this.ReportPropertyChanging("IdTerritory");
                this._IdTerritory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdTerritory");
                this.OnIdTerritoryChanged();
            }
        }
        private int _IdTerritory;
        partial void OnIdTerritoryChanging(int value);
        partial void OnIdTerritoryChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this.ReportPropertyChanging("Number");
                this._Number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Number");
                this.OnNumberChanged();
            }
        }
        private global::System.Nullable<int> _Number;
        partial void OnNumberChanging(global::System.Nullable<int> value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Directions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_directions_territories", "Directions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Direction> Directions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Direction>("TerritoriesModel.FK_directions_territories", "Directions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Direction>("TerritoriesModel.FK_directions_territories", "Directions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tours in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_tours_territories", "Tours")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tour> Tours
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tour>("TerritoriesModel.FK_tours_territories", "Tours");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Tour>("TerritoriesModel.FK_tours_territories", "Tours", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "TerritoriesGeopositions", "GeoPositions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GeoPosition> GeoPositions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GeoPosition>("TerritoriesModel.TerritoriesGeopositions", "GeoPositions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GeoPosition>("TerritoriesModel.TerritoriesGeopositions", "GeoPositions", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.Tour in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdTerritory
    /// TourNumber
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="Tour")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tour : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tour object.
        /// </summary>
        /// <param name="idTerritory">Initial value of IdTerritory.</param>
        /// <param name="beginDate">Initial value of BeginDate.</param>
        /// <param name="tourNumber">Initial value of TourNumber.</param>
        public static Tour CreateTour(int idTerritory, global::System.DateTime beginDate, int tourNumber)
        {
            Tour tour = new Tour();
            tour.IdTerritory = idTerritory;
            tour.BeginDate = beginDate;
            tour.TourNumber = tourNumber;
            return tour;
        }
        /// <summary>
        /// There are no comments for Property IdTerritory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTerritory
        {
            get
            {
                return this._IdTerritory;
            }
            set
            {
                this.OnIdTerritoryChanging(value);
                this.ReportPropertyChanging("IdTerritory");
                this._IdTerritory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdTerritory");
                this.OnIdTerritoryChanged();
            }
        }
        private int _IdTerritory;
        partial void OnIdTerritoryChanging(int value);
        partial void OnIdTerritoryChanged();
        /// <summary>
        /// There are no comments for Property BeginDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime BeginDate
        {
            get
            {
                return this._BeginDate;
            }
            set
            {
                this.OnBeginDateChanging(value);
                this.ReportPropertyChanging("BeginDate");
                this._BeginDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BeginDate");
                this.OnBeginDateChanged();
            }
        }
        private global::System.DateTime _BeginDate;
        partial void OnBeginDateChanging(global::System.DateTime value);
        partial void OnBeginDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this.ReportPropertyChanging("EndDate");
                this._EndDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDate");
                this.OnEndDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property TourNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TourNumber
        {
            get
            {
                return this._TourNumber;
            }
            set
            {
                this.OnTourNumberChanging(value);
                this.ReportPropertyChanging("TourNumber");
                this._TourNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TourNumber");
                this.OnTourNumberChanged();
            }
        }
        private int _TourNumber;
        partial void OnTourNumberChanging(int value);
        partial void OnTourNumberChanged();
        /// <summary>
        /// There are no comments for Publisher in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_tours_publishers", "Publishers")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Publisher Publisher
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Publisher>("TerritoriesModel.FK_tours_publishers", "Publishers").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Publisher>("TerritoriesModel.FK_tours_publishers", "Publishers").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Publisher in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Publisher> PublisherReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Publisher>("TerritoriesModel.FK_tours_publishers", "Publishers");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Publisher>("TerritoriesModel.FK_tours_publishers", "Publishers", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Territory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "FK_tours_territories", "Territories")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Territory Territory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Territory>("TerritoriesModel.FK_tours_territories", "Territories").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Territory>("TerritoriesModel.FK_tours_territories", "Territories").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Territory in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Territory> TerritoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Territory>("TerritoriesModel.FK_tours_territories", "Territories");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Territory>("TerritoriesModel.FK_tours_territories", "Territories", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TerritoriesModel.GeoPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdGeoposition
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TerritoriesModel", Name="GeoPosition")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GeoPosition : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new GeoPosition object.
        /// </summary>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="idGeoposition">Initial value of IdGeoposition.</param>
        /// <param name="latitude">Initial value of Latitude.</param>
        /// <param name="longitude">Initial value of Longitude.</param>
        public static GeoPosition CreateGeoPosition(global::System.DateTime date, int idGeoposition, double latitude, double longitude)
        {
            GeoPosition geoPosition = new GeoPosition();
            geoPosition.Date = date;
            geoPosition.IdGeoposition = idGeoposition;
            geoPosition.Latitude = latitude;
            geoPosition.Longitude = longitude;
            return geoPosition;
        }
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property IdGeoposition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGeoposition
        {
            get
            {
                return this._IdGeoposition;
            }
            set
            {
                this.OnIdGeopositionChanging(value);
                this.ReportPropertyChanging("IdGeoposition");
                this._IdGeoposition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdGeoposition");
                this.OnIdGeopositionChanged();
            }
        }
        private int _IdGeoposition;
        partial void OnIdGeopositionChanging(int value);
        partial void OnIdGeopositionChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this.ReportPropertyChanging("Latitude");
                this._Latitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Latitude");
                this.OnLatitudeChanged();
            }
        }
        private double _Latitude;
        partial void OnLatitudeChanging(double value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this.ReportPropertyChanging("Longitude");
                this._Longitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Longitude");
                this.OnLongitudeChanged();
            }
        }
        private double _Longitude;
        partial void OnLongitudeChanging(double value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "CitiesGeopositions", "City")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<City> Cities
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<City>("TerritoriesModel.CitiesGeopositions", "City");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<City>("TerritoriesModel.CitiesGeopositions", "City", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Departments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "DepartmentsGeopositions", "Department")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Department> Departments
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Department>("TerritoriesModel.DepartmentsGeopositions", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Department>("TerritoriesModel.DepartmentsGeopositions", "Department", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Directions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "DirectionsGeopositions", "Direction")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Direction> Directions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Direction>("TerritoriesModel.DirectionsGeopositions", "Direction");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Direction>("TerritoriesModel.DirectionsGeopositions", "Direction", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Territories in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TerritoriesModel", "TerritoriesGeopositions", "Territory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Territory> Territories
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Territory>("TerritoriesModel.TerritoriesGeopositions", "Territory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Territory>("TerritoriesModel.TerritoriesGeopositions", "Territory", value);
                }
            }
        }
    }
}
